# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Tests on Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'maven'
        check-latest: true
    - name: Run tests
      continue-on-error: true
      run: mvn test -Dtest="api.tests.RestfulBooker"
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'target/surefire-reports/TEST-*.xml'
